[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"

[[constraint]]
  branch = "master"
  name = "github.com/jackspirou/syscerts"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.3.0"

[prune]
  go-tests = true
  unused-packages = true
