// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new team API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for team API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AttachTeamToMod(params *AttachTeamToModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToModOK, error)

	AttachTeamToPack(params *AttachTeamToPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToPackOK, error)

	AttachTeamToUser(params *AttachTeamToUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToUserOK, error)

	CreateTeam(params *CreateTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateTeamOK, error)

	DeleteTeam(params *DeleteTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamOK, error)

	DeleteTeamFromMod(params *DeleteTeamFromModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromModOK, error)

	DeleteTeamFromPack(params *DeleteTeamFromPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromPackOK, error)

	DeleteTeamFromUser(params *DeleteTeamFromUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromUserOK, error)

	ListTeamMods(params *ListTeamModsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamModsOK, error)

	ListTeamPacks(params *ListTeamPacksParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamPacksOK, error)

	ListTeamUsers(params *ListTeamUsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamUsersOK, error)

	ListTeams(params *ListTeamsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamsOK, error)

	PermitTeamMod(params *PermitTeamModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamModOK, error)

	PermitTeamPack(params *PermitTeamPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamPackOK, error)

	PermitTeamUser(params *PermitTeamUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamUserOK, error)

	ShowTeam(params *ShowTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ShowTeamOK, error)

	UpdateTeam(params *UpdateTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateTeamOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AttachTeamToMod attaches a mod to team
*/
func (a *Client) AttachTeamToMod(params *AttachTeamToModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToModOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAttachTeamToModParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AttachTeamToMod",
		Method:             "POST",
		PathPattern:        "/teams/{team_id}/mods",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AttachTeamToModReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AttachTeamToModOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AttachTeamToModDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
AttachTeamToPack attaches a pack to team
*/
func (a *Client) AttachTeamToPack(params *AttachTeamToPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToPackOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAttachTeamToPackParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AttachTeamToPack",
		Method:             "POST",
		PathPattern:        "/teams/{team_id}/packs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AttachTeamToPackReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AttachTeamToPackOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AttachTeamToPackDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
AttachTeamToUser attaches a user to team
*/
func (a *Client) AttachTeamToUser(params *AttachTeamToUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*AttachTeamToUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAttachTeamToUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AttachTeamToUser",
		Method:             "POST",
		PathPattern:        "/teams/{team_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AttachTeamToUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AttachTeamToUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AttachTeamToUserDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
CreateTeam creates a new team
*/
func (a *Client) CreateTeam(params *CreateTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateTeamOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateTeamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateTeam",
		Method:             "POST",
		PathPattern:        "/teams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateTeamReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateTeamOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateTeamDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteTeam deletes a specific team
*/
func (a *Client) DeleteTeam(params *DeleteTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteTeamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeam",
		Method:             "DELETE",
		PathPattern:        "/teams/{team_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTeamReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteTeamOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteTeamDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteTeamFromMod removes a mod from team
*/
func (a *Client) DeleteTeamFromMod(params *DeleteTeamFromModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromModOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteTeamFromModParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeamFromMod",
		Method:             "DELETE",
		PathPattern:        "/teams/{team_id}/mods",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTeamFromModReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteTeamFromModOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteTeamFromModDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteTeamFromPack removes a pack from team
*/
func (a *Client) DeleteTeamFromPack(params *DeleteTeamFromPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromPackOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteTeamFromPackParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeamFromPack",
		Method:             "DELETE",
		PathPattern:        "/teams/{team_id}/packs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTeamFromPackReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteTeamFromPackOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteTeamFromPackDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
DeleteTeamFromUser removes a user from team
*/
func (a *Client) DeleteTeamFromUser(params *DeleteTeamFromUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteTeamFromUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteTeamFromUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteTeamFromUser",
		Method:             "DELETE",
		PathPattern:        "/teams/{team_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteTeamFromUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteTeamFromUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteTeamFromUserDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListTeamMods fetches all mods attached to team
*/
func (a *Client) ListTeamMods(params *ListTeamModsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamModsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTeamModsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListTeamMods",
		Method:             "GET",
		PathPattern:        "/teams/{team_id}/mods",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTeamModsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListTeamModsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListTeamModsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListTeamPacks fetches all packs attached to team
*/
func (a *Client) ListTeamPacks(params *ListTeamPacksParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamPacksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTeamPacksParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListTeamPacks",
		Method:             "GET",
		PathPattern:        "/teams/{team_id}/packs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTeamPacksReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListTeamPacksOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListTeamPacksDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListTeamUsers fetches all users attached to team
*/
func (a *Client) ListTeamUsers(params *ListTeamUsersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamUsersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTeamUsersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListTeamUsers",
		Method:             "GET",
		PathPattern:        "/teams/{team_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTeamUsersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListTeamUsersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListTeamUsersDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ListTeams fetches all available teams
*/
func (a *Client) ListTeams(params *ListTeamsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListTeamsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTeamsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListTeams",
		Method:             "GET",
		PathPattern:        "/teams",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTeamsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListTeamsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ListTeamsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PermitTeamMod updates mod perms for team
*/
func (a *Client) PermitTeamMod(params *PermitTeamModParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamModOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPermitTeamModParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PermitTeamMod",
		Method:             "PUT",
		PathPattern:        "/teams/{team_id}/mods",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PermitTeamModReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PermitTeamModOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PermitTeamModDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PermitTeamPack updates pack perms for team
*/
func (a *Client) PermitTeamPack(params *PermitTeamPackParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamPackOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPermitTeamPackParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PermitTeamPack",
		Method:             "PUT",
		PathPattern:        "/teams/{team_id}/packs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PermitTeamPackReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PermitTeamPackOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PermitTeamPackDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PermitTeamUser updates user perms for team
*/
func (a *Client) PermitTeamUser(params *PermitTeamUserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PermitTeamUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPermitTeamUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PermitTeamUser",
		Method:             "PUT",
		PathPattern:        "/teams/{team_id}/users",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PermitTeamUserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PermitTeamUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PermitTeamUserDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
ShowTeam fetches a specific team
*/
func (a *Client) ShowTeam(params *ShowTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ShowTeamOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewShowTeamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ShowTeam",
		Method:             "GET",
		PathPattern:        "/teams/{team_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ShowTeamReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ShowTeamOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ShowTeamDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
UpdateTeam updates a specific team
*/
func (a *Client) UpdateTeam(params *UpdateTeamParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateTeamOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateTeamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "UpdateTeam",
		Method:             "PUT",
		PathPattern:        "/teams/{team_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateTeamReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateTeamOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*UpdateTeamDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
