// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/models"
)

// NewAttachUserToModParams creates a new AttachUserToModParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAttachUserToModParams() *AttachUserToModParams {
	return &AttachUserToModParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAttachUserToModParamsWithTimeout creates a new AttachUserToModParams object
// with the ability to set a timeout on a request.
func NewAttachUserToModParamsWithTimeout(timeout time.Duration) *AttachUserToModParams {
	return &AttachUserToModParams{
		timeout: timeout,
	}
}

// NewAttachUserToModParamsWithContext creates a new AttachUserToModParams object
// with the ability to set a context for a request.
func NewAttachUserToModParamsWithContext(ctx context.Context) *AttachUserToModParams {
	return &AttachUserToModParams{
		Context: ctx,
	}
}

// NewAttachUserToModParamsWithHTTPClient creates a new AttachUserToModParams object
// with the ability to set a custom HTTPClient for a request.
func NewAttachUserToModParamsWithHTTPClient(client *http.Client) *AttachUserToModParams {
	return &AttachUserToModParams{
		HTTPClient: client,
	}
}

/*
AttachUserToModParams contains all the parameters to send to the API endpoint

	for the attach user to mod operation.

	Typically these are written to a http.Request.
*/
type AttachUserToModParams struct {

	/* UserID.

	   A user UUID or slug
	*/
	UserID string

	/* UserMod.

	   The user mod data to assign
	*/
	UserMod *models.UserModParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the attach user to mod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachUserToModParams) WithDefaults() *AttachUserToModParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the attach user to mod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AttachUserToModParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the attach user to mod params
func (o *AttachUserToModParams) WithTimeout(timeout time.Duration) *AttachUserToModParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the attach user to mod params
func (o *AttachUserToModParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the attach user to mod params
func (o *AttachUserToModParams) WithContext(ctx context.Context) *AttachUserToModParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the attach user to mod params
func (o *AttachUserToModParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the attach user to mod params
func (o *AttachUserToModParams) WithHTTPClient(client *http.Client) *AttachUserToModParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the attach user to mod params
func (o *AttachUserToModParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the attach user to mod params
func (o *AttachUserToModParams) WithUserID(userID string) *AttachUserToModParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the attach user to mod params
func (o *AttachUserToModParams) SetUserID(userID string) {
	o.UserID = userID
}

// WithUserMod adds the userMod to the attach user to mod params
func (o *AttachUserToModParams) WithUserMod(userMod *models.UserModParams) *AttachUserToModParams {
	o.SetUserMod(userMod)
	return o
}

// SetUserMod adds the userMod to the attach user to mod params
func (o *AttachUserToModParams) SetUserMod(userMod *models.UserModParams) {
	o.UserMod = userMod
}

// WriteToRequest writes these params to a swagger request
func (o *AttachUserToModParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}
	if o.UserMod != nil {
		if err := r.SetBodyParam(o.UserMod); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
