// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListUserPacksParams creates a new ListUserPacksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListUserPacksParams() *ListUserPacksParams {
	return &ListUserPacksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListUserPacksParamsWithTimeout creates a new ListUserPacksParams object
// with the ability to set a timeout on a request.
func NewListUserPacksParamsWithTimeout(timeout time.Duration) *ListUserPacksParams {
	return &ListUserPacksParams{
		timeout: timeout,
	}
}

// NewListUserPacksParamsWithContext creates a new ListUserPacksParams object
// with the ability to set a context for a request.
func NewListUserPacksParamsWithContext(ctx context.Context) *ListUserPacksParams {
	return &ListUserPacksParams{
		Context: ctx,
	}
}

// NewListUserPacksParamsWithHTTPClient creates a new ListUserPacksParams object
// with the ability to set a custom HTTPClient for a request.
func NewListUserPacksParamsWithHTTPClient(client *http.Client) *ListUserPacksParams {
	return &ListUserPacksParams{
		HTTPClient: client,
	}
}

/* ListUserPacksParams contains all the parameters to send to the API endpoint
   for the list user packs operation.

   Typically these are written to a http.Request.
*/
type ListUserPacksParams struct {

	/* UserID.

	   A user UUID or slug
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list user packs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserPacksParams) WithDefaults() *ListUserPacksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list user packs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUserPacksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list user packs params
func (o *ListUserPacksParams) WithTimeout(timeout time.Duration) *ListUserPacksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list user packs params
func (o *ListUserPacksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list user packs params
func (o *ListUserPacksParams) WithContext(ctx context.Context) *ListUserPacksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list user packs params
func (o *ListUserPacksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list user packs params
func (o *ListUserPacksParams) WithHTTPClient(client *http.Client) *ListUserPacksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list user packs params
func (o *ListUserPacksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the list user packs params
func (o *ListUserPacksParams) WithUserID(userID string) *ListUserPacksParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the list user packs params
func (o *ListUserPacksParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ListUserPacksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
