// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kleister/kleister-go/models"
)

// NewPermitUserModParams creates a new PermitUserModParams object
// with the default values initialized.
func NewPermitUserModParams() *PermitUserModParams {
	var ()
	return &PermitUserModParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPermitUserModParamsWithTimeout creates a new PermitUserModParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPermitUserModParamsWithTimeout(timeout time.Duration) *PermitUserModParams {
	var ()
	return &PermitUserModParams{

		timeout: timeout,
	}
}

// NewPermitUserModParamsWithContext creates a new PermitUserModParams object
// with the default values initialized, and the ability to set a context for a request
func NewPermitUserModParamsWithContext(ctx context.Context) *PermitUserModParams {
	var ()
	return &PermitUserModParams{

		Context: ctx,
	}
}

// NewPermitUserModParamsWithHTTPClient creates a new PermitUserModParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPermitUserModParamsWithHTTPClient(client *http.Client) *PermitUserModParams {
	var ()
	return &PermitUserModParams{
		HTTPClient: client,
	}
}

/*PermitUserModParams contains all the parameters to send to the API endpoint
for the permit user mod operation typically these are written to a http.Request
*/
type PermitUserModParams struct {

	/*Params
	  The user mod data to update

	*/
	Params *models.UserModParams
	/*UserID
	  A user UUID or slug

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the permit user mod params
func (o *PermitUserModParams) WithTimeout(timeout time.Duration) *PermitUserModParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the permit user mod params
func (o *PermitUserModParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the permit user mod params
func (o *PermitUserModParams) WithContext(ctx context.Context) *PermitUserModParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the permit user mod params
func (o *PermitUserModParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the permit user mod params
func (o *PermitUserModParams) WithHTTPClient(client *http.Client) *PermitUserModParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the permit user mod params
func (o *PermitUserModParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the permit user mod params
func (o *PermitUserModParams) WithParams(params *models.UserModParams) *PermitUserModParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the permit user mod params
func (o *PermitUserModParams) SetParams(params *models.UserModParams) {
	o.Params = params
}

// WithUserID adds the userID to the permit user mod params
func (o *PermitUserModParams) WithUserID(userID string) *PermitUserModParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the permit user mod params
func (o *PermitUserModParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *PermitUserModParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
