// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/v1/models"
)

// DeleteBuildReader is a Reader for the DeleteBuild structure.
type DeleteBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBuildBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteBuildForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteBuildNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteBuildDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteBuildOK creates a DeleteBuildOK with default headers values
func NewDeleteBuildOK() *DeleteBuildOK {
	return &DeleteBuildOK{}
}

/*
DeleteBuildOK describes a response with status code 200, with default header values.

Plain success message
*/
type DeleteBuildOK struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this delete build o k response has a 2xx status code
func (o *DeleteBuildOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete build o k response has a 3xx status code
func (o *DeleteBuildOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete build o k response has a 4xx status code
func (o *DeleteBuildOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete build o k response has a 5xx status code
func (o *DeleteBuildOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete build o k response a status code equal to that given
func (o *DeleteBuildOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete build o k response
func (o *DeleteBuildOK) Code() int {
	return 200
}

func (o *DeleteBuildOK) Error() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildOK  %+v", 200, o.Payload)
}

func (o *DeleteBuildOK) String() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildOK  %+v", 200, o.Payload)
}

func (o *DeleteBuildOK) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *DeleteBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildBadRequest creates a DeleteBuildBadRequest with default headers values
func NewDeleteBuildBadRequest() *DeleteBuildBadRequest {
	return &DeleteBuildBadRequest{}
}

/*
DeleteBuildBadRequest describes a response with status code 400, with default header values.

Failed to delete the build
*/
type DeleteBuildBadRequest struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this delete build bad request response has a 2xx status code
func (o *DeleteBuildBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete build bad request response has a 3xx status code
func (o *DeleteBuildBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete build bad request response has a 4xx status code
func (o *DeleteBuildBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete build bad request response has a 5xx status code
func (o *DeleteBuildBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete build bad request response a status code equal to that given
func (o *DeleteBuildBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete build bad request response
func (o *DeleteBuildBadRequest) Code() int {
	return 400
}

func (o *DeleteBuildBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteBuildBadRequest) String() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteBuildBadRequest) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *DeleteBuildBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildForbidden creates a DeleteBuildForbidden with default headers values
func NewDeleteBuildForbidden() *DeleteBuildForbidden {
	return &DeleteBuildForbidden{}
}

/*
DeleteBuildForbidden describes a response with status code 403, with default header values.

User is not authorized
*/
type DeleteBuildForbidden struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this delete build forbidden response has a 2xx status code
func (o *DeleteBuildForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete build forbidden response has a 3xx status code
func (o *DeleteBuildForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete build forbidden response has a 4xx status code
func (o *DeleteBuildForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete build forbidden response has a 5xx status code
func (o *DeleteBuildForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete build forbidden response a status code equal to that given
func (o *DeleteBuildForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete build forbidden response
func (o *DeleteBuildForbidden) Code() int {
	return 403
}

func (o *DeleteBuildForbidden) Error() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildForbidden  %+v", 403, o.Payload)
}

func (o *DeleteBuildForbidden) String() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildForbidden  %+v", 403, o.Payload)
}

func (o *DeleteBuildForbidden) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *DeleteBuildForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildNotFound creates a DeleteBuildNotFound with default headers values
func NewDeleteBuildNotFound() *DeleteBuildNotFound {
	return &DeleteBuildNotFound{}
}

/*
DeleteBuildNotFound describes a response with status code 404, with default header values.

Build or pack not found
*/
type DeleteBuildNotFound struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this delete build not found response has a 2xx status code
func (o *DeleteBuildNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete build not found response has a 3xx status code
func (o *DeleteBuildNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete build not found response has a 4xx status code
func (o *DeleteBuildNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete build not found response has a 5xx status code
func (o *DeleteBuildNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete build not found response a status code equal to that given
func (o *DeleteBuildNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete build not found response
func (o *DeleteBuildNotFound) Code() int {
	return 404
}

func (o *DeleteBuildNotFound) Error() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildNotFound  %+v", 404, o.Payload)
}

func (o *DeleteBuildNotFound) String() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] deleteBuildNotFound  %+v", 404, o.Payload)
}

func (o *DeleteBuildNotFound) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *DeleteBuildNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBuildDefault creates a DeleteBuildDefault with default headers values
func NewDeleteBuildDefault(code int) *DeleteBuildDefault {
	return &DeleteBuildDefault{
		_statusCode: code,
	}
}

/*
DeleteBuildDefault describes a response with status code -1, with default header values.

Some error unrelated to the handler
*/
type DeleteBuildDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// IsSuccess returns true when this delete build default response has a 2xx status code
func (o *DeleteBuildDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete build default response has a 3xx status code
func (o *DeleteBuildDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete build default response has a 4xx status code
func (o *DeleteBuildDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete build default response has a 5xx status code
func (o *DeleteBuildDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete build default response a status code equal to that given
func (o *DeleteBuildDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete build default response
func (o *DeleteBuildDefault) Code() int {
	return o._statusCode
}

func (o *DeleteBuildDefault) Error() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] DeleteBuild default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteBuildDefault) String() string {
	return fmt.Sprintf("[DELETE /packs/{pack_id}/builds/{build_id}][%d] DeleteBuild default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteBuildDefault) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *DeleteBuildDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
