// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPacksParams creates a new ListPacksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPacksParams() *ListPacksParams {
	return &ListPacksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPacksParamsWithTimeout creates a new ListPacksParams object
// with the ability to set a timeout on a request.
func NewListPacksParamsWithTimeout(timeout time.Duration) *ListPacksParams {
	return &ListPacksParams{
		timeout: timeout,
	}
}

// NewListPacksParamsWithContext creates a new ListPacksParams object
// with the ability to set a context for a request.
func NewListPacksParamsWithContext(ctx context.Context) *ListPacksParams {
	return &ListPacksParams{
		Context: ctx,
	}
}

// NewListPacksParamsWithHTTPClient creates a new ListPacksParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPacksParamsWithHTTPClient(client *http.Client) *ListPacksParams {
	return &ListPacksParams{
		HTTPClient: client,
	}
}

/* ListPacksParams contains all the parameters to send to the API endpoint
   for the list packs operation.

   Typically these are written to a http.Request.
*/
type ListPacksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list packs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPacksParams) WithDefaults() *ListPacksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list packs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPacksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list packs params
func (o *ListPacksParams) WithTimeout(timeout time.Duration) *ListPacksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list packs params
func (o *ListPacksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list packs params
func (o *ListPacksParams) WithContext(ctx context.Context) *ListPacksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list packs params
func (o *ListPacksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list packs params
func (o *ListPacksParams) WithHTTPClient(client *http.Client) *ListPacksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list packs params
func (o *ListPacksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPacksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
