// Code generated by go-swagger; DO NOT EDIT.

package kleister

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/kleister/auth"
	"github.com/kleister/kleister-go/kleister/fabric"
	"github.com/kleister/kleister-go/kleister/forge"
	"github.com/kleister/kleister-go/kleister/minecraft"
	"github.com/kleister/kleister-go/kleister/mod"
	"github.com/kleister/kleister-go/kleister/neoforge"
	"github.com/kleister/kleister-go/kleister/pack"
	"github.com/kleister/kleister-go/kleister/profile"
	"github.com/kleister/kleister-go/kleister/quilt"
	"github.com/kleister/kleister-go/kleister/team"
	"github.com/kleister/kleister-go/kleister/user"
)

// Default kleister HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "try.kleister.eu"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new kleister HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Kleister {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new kleister HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Kleister {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new kleister client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Kleister {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Kleister)
	cli.Transport = transport
	cli.Auth = auth.New(transport, formats)
	cli.Fabric = fabric.New(transport, formats)
	cli.Forge = forge.New(transport, formats)
	cli.Minecraft = minecraft.New(transport, formats)
	cli.Mod = mod.New(transport, formats)
	cli.Neoforge = neoforge.New(transport, formats)
	cli.Pack = pack.New(transport, formats)
	cli.Profile = profile.New(transport, formats)
	cli.Quilt = quilt.New(transport, formats)
	cli.Team = team.New(transport, formats)
	cli.User = user.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Kleister is a client for kleister
type Kleister struct {
	Auth auth.ClientService

	Fabric fabric.ClientService

	Forge forge.ClientService

	Minecraft minecraft.ClientService

	Mod mod.ClientService

	Neoforge neoforge.ClientService

	Pack pack.ClientService

	Profile profile.ClientService

	Quilt quilt.ClientService

	Team team.ClientService

	User user.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Kleister) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Auth.SetTransport(transport)
	c.Fabric.SetTransport(transport)
	c.Forge.SetTransport(transport)
	c.Minecraft.SetTransport(transport)
	c.Mod.SetTransport(transport)
	c.Neoforge.SetTransport(transport)
	c.Pack.SetTransport(transport)
	c.Profile.SetTransport(transport)
	c.Quilt.SetTransport(transport)
	c.Team.SetTransport(transport)
	c.User.SetTransport(transport)
}
