// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/v1/models"
)

// AppendVersionToBuildReader is a Reader for the AppendVersionToBuild structure.
type AppendVersionToBuildReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AppendVersionToBuildReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAppendVersionToBuildOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewAppendVersionToBuildForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAppendVersionToBuildNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewAppendVersionToBuildPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewAppendVersionToBuildUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAppendVersionToBuildDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAppendVersionToBuildOK creates a AppendVersionToBuildOK with default headers values
func NewAppendVersionToBuildOK() *AppendVersionToBuildOK {
	return &AppendVersionToBuildOK{}
}

/*
AppendVersionToBuildOK describes a response with status code 200, with default header values.

Plain success message
*/
type AppendVersionToBuildOK struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this append version to build o k response has a 2xx status code
func (o *AppendVersionToBuildOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this append version to build o k response has a 3xx status code
func (o *AppendVersionToBuildOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this append version to build o k response has a 4xx status code
func (o *AppendVersionToBuildOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this append version to build o k response has a 5xx status code
func (o *AppendVersionToBuildOK) IsServerError() bool {
	return false
}

// IsCode returns true when this append version to build o k response a status code equal to that given
func (o *AppendVersionToBuildOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the append version to build o k response
func (o *AppendVersionToBuildOK) Code() int {
	return 200
}

func (o *AppendVersionToBuildOK) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildOK  %+v", 200, o.Payload)
}

func (o *AppendVersionToBuildOK) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildOK  %+v", 200, o.Payload)
}

func (o *AppendVersionToBuildOK) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *AppendVersionToBuildOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppendVersionToBuildForbidden creates a AppendVersionToBuildForbidden with default headers values
func NewAppendVersionToBuildForbidden() *AppendVersionToBuildForbidden {
	return &AppendVersionToBuildForbidden{}
}

/*
AppendVersionToBuildForbidden describes a response with status code 403, with default header values.

User is not authorized
*/
type AppendVersionToBuildForbidden struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this append version to build forbidden response has a 2xx status code
func (o *AppendVersionToBuildForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this append version to build forbidden response has a 3xx status code
func (o *AppendVersionToBuildForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this append version to build forbidden response has a 4xx status code
func (o *AppendVersionToBuildForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this append version to build forbidden response has a 5xx status code
func (o *AppendVersionToBuildForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this append version to build forbidden response a status code equal to that given
func (o *AppendVersionToBuildForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the append version to build forbidden response
func (o *AppendVersionToBuildForbidden) Code() int {
	return 403
}

func (o *AppendVersionToBuildForbidden) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildForbidden  %+v", 403, o.Payload)
}

func (o *AppendVersionToBuildForbidden) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildForbidden  %+v", 403, o.Payload)
}

func (o *AppendVersionToBuildForbidden) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *AppendVersionToBuildForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppendVersionToBuildNotFound creates a AppendVersionToBuildNotFound with default headers values
func NewAppendVersionToBuildNotFound() *AppendVersionToBuildNotFound {
	return &AppendVersionToBuildNotFound{}
}

/*
AppendVersionToBuildNotFound describes a response with status code 404, with default header values.

Build, version or mod not found
*/
type AppendVersionToBuildNotFound struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this append version to build not found response has a 2xx status code
func (o *AppendVersionToBuildNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this append version to build not found response has a 3xx status code
func (o *AppendVersionToBuildNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this append version to build not found response has a 4xx status code
func (o *AppendVersionToBuildNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this append version to build not found response has a 5xx status code
func (o *AppendVersionToBuildNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this append version to build not found response a status code equal to that given
func (o *AppendVersionToBuildNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the append version to build not found response
func (o *AppendVersionToBuildNotFound) Code() int {
	return 404
}

func (o *AppendVersionToBuildNotFound) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildNotFound  %+v", 404, o.Payload)
}

func (o *AppendVersionToBuildNotFound) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildNotFound  %+v", 404, o.Payload)
}

func (o *AppendVersionToBuildNotFound) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *AppendVersionToBuildNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppendVersionToBuildPreconditionFailed creates a AppendVersionToBuildPreconditionFailed with default headers values
func NewAppendVersionToBuildPreconditionFailed() *AppendVersionToBuildPreconditionFailed {
	return &AppendVersionToBuildPreconditionFailed{}
}

/*
AppendVersionToBuildPreconditionFailed describes a response with status code 412, with default header values.

Build is already assigned
*/
type AppendVersionToBuildPreconditionFailed struct {
	Payload *models.GeneralError
}

// IsSuccess returns true when this append version to build precondition failed response has a 2xx status code
func (o *AppendVersionToBuildPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this append version to build precondition failed response has a 3xx status code
func (o *AppendVersionToBuildPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this append version to build precondition failed response has a 4xx status code
func (o *AppendVersionToBuildPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this append version to build precondition failed response has a 5xx status code
func (o *AppendVersionToBuildPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this append version to build precondition failed response a status code equal to that given
func (o *AppendVersionToBuildPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the append version to build precondition failed response
func (o *AppendVersionToBuildPreconditionFailed) Code() int {
	return 412
}

func (o *AppendVersionToBuildPreconditionFailed) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildPreconditionFailed  %+v", 412, o.Payload)
}

func (o *AppendVersionToBuildPreconditionFailed) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildPreconditionFailed  %+v", 412, o.Payload)
}

func (o *AppendVersionToBuildPreconditionFailed) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *AppendVersionToBuildPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppendVersionToBuildUnprocessableEntity creates a AppendVersionToBuildUnprocessableEntity with default headers values
func NewAppendVersionToBuildUnprocessableEntity() *AppendVersionToBuildUnprocessableEntity {
	return &AppendVersionToBuildUnprocessableEntity{}
}

/*
AppendVersionToBuildUnprocessableEntity describes a response with status code 422, with default header values.

Failed to validate request
*/
type AppendVersionToBuildUnprocessableEntity struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this append version to build unprocessable entity response has a 2xx status code
func (o *AppendVersionToBuildUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this append version to build unprocessable entity response has a 3xx status code
func (o *AppendVersionToBuildUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this append version to build unprocessable entity response has a 4xx status code
func (o *AppendVersionToBuildUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this append version to build unprocessable entity response has a 5xx status code
func (o *AppendVersionToBuildUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this append version to build unprocessable entity response a status code equal to that given
func (o *AppendVersionToBuildUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the append version to build unprocessable entity response
func (o *AppendVersionToBuildUnprocessableEntity) Code() int {
	return 422
}

func (o *AppendVersionToBuildUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *AppendVersionToBuildUnprocessableEntity) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] appendVersionToBuildUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *AppendVersionToBuildUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *AppendVersionToBuildUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAppendVersionToBuildDefault creates a AppendVersionToBuildDefault with default headers values
func NewAppendVersionToBuildDefault(code int) *AppendVersionToBuildDefault {
	return &AppendVersionToBuildDefault{
		_statusCode: code,
	}
}

/*
AppendVersionToBuildDefault describes a response with status code -1, with default header values.

Some error unrelated to the handler
*/
type AppendVersionToBuildDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// IsSuccess returns true when this append version to build default response has a 2xx status code
func (o *AppendVersionToBuildDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this append version to build default response has a 3xx status code
func (o *AppendVersionToBuildDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this append version to build default response has a 4xx status code
func (o *AppendVersionToBuildDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this append version to build default response has a 5xx status code
func (o *AppendVersionToBuildDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this append version to build default response a status code equal to that given
func (o *AppendVersionToBuildDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the append version to build default response
func (o *AppendVersionToBuildDefault) Code() int {
	return o._statusCode
}

func (o *AppendVersionToBuildDefault) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] AppendVersionToBuild default  %+v", o._statusCode, o.Payload)
}

func (o *AppendVersionToBuildDefault) String() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions/{version_id}/builds][%d] AppendVersionToBuild default  %+v", o._statusCode, o.Payload)
}

func (o *AppendVersionToBuildDefault) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *AppendVersionToBuildDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
