// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/v1/models"
)

// CreateVersionReader is a Reader for the CreateVersion structure.
type CreateVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewCreateVersionPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateVersionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateVersionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateVersionOK creates a CreateVersionOK with default headers values
func NewCreateVersionOK() *CreateVersionOK {
	return &CreateVersionOK{}
}

/* CreateVersionOK describes a response with status code 200, with default header values.

The created version data
*/
type CreateVersionOK struct {
	Payload *models.Version
}

func (o *CreateVersionOK) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions][%d] createVersionOK  %+v", 200, o.Payload)
}
func (o *CreateVersionOK) GetPayload() *models.Version {
	return o.Payload
}

func (o *CreateVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Version)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVersionForbidden creates a CreateVersionForbidden with default headers values
func NewCreateVersionForbidden() *CreateVersionForbidden {
	return &CreateVersionForbidden{}
}

/* CreateVersionForbidden describes a response with status code 403, with default header values.

User is not authorized
*/
type CreateVersionForbidden struct {
	Payload *models.GeneralError
}

func (o *CreateVersionForbidden) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions][%d] createVersionForbidden  %+v", 403, o.Payload)
}
func (o *CreateVersionForbidden) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *CreateVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVersionPreconditionFailed creates a CreateVersionPreconditionFailed with default headers values
func NewCreateVersionPreconditionFailed() *CreateVersionPreconditionFailed {
	return &CreateVersionPreconditionFailed{}
}

/* CreateVersionPreconditionFailed describes a response with status code 412, with default header values.

Failed to parse request body
*/
type CreateVersionPreconditionFailed struct {
	Payload *models.GeneralError
}

func (o *CreateVersionPreconditionFailed) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions][%d] createVersionPreconditionFailed  %+v", 412, o.Payload)
}
func (o *CreateVersionPreconditionFailed) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *CreateVersionPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVersionUnprocessableEntity creates a CreateVersionUnprocessableEntity with default headers values
func NewCreateVersionUnprocessableEntity() *CreateVersionUnprocessableEntity {
	return &CreateVersionUnprocessableEntity{}
}

/* CreateVersionUnprocessableEntity describes a response with status code 422, with default header values.

Failed to validate request
*/
type CreateVersionUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreateVersionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions][%d] createVersionUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateVersionUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateVersionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVersionDefault creates a CreateVersionDefault with default headers values
func NewCreateVersionDefault(code int) *CreateVersionDefault {
	return &CreateVersionDefault{
		_statusCode: code,
	}
}

/* CreateVersionDefault describes a response with status code -1, with default header values.

Some error unrelated to the handler
*/
type CreateVersionDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// Code gets the status code for the create version default response
func (o *CreateVersionDefault) Code() int {
	return o._statusCode
}

func (o *CreateVersionDefault) Error() string {
	return fmt.Sprintf("[POST /mods/{mod_id}/versions][%d] CreateVersion default  %+v", o._statusCode, o.Payload)
}
func (o *CreateVersionDefault) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *CreateVersionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
