// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteModParams creates a new DeleteModParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteModParams() *DeleteModParams {
	return &DeleteModParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteModParamsWithTimeout creates a new DeleteModParams object
// with the ability to set a timeout on a request.
func NewDeleteModParamsWithTimeout(timeout time.Duration) *DeleteModParams {
	return &DeleteModParams{
		timeout: timeout,
	}
}

// NewDeleteModParamsWithContext creates a new DeleteModParams object
// with the ability to set a context for a request.
func NewDeleteModParamsWithContext(ctx context.Context) *DeleteModParams {
	return &DeleteModParams{
		Context: ctx,
	}
}

// NewDeleteModParamsWithHTTPClient creates a new DeleteModParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteModParamsWithHTTPClient(client *http.Client) *DeleteModParams {
	return &DeleteModParams{
		HTTPClient: client,
	}
}

/*
DeleteModParams contains all the parameters to send to the API endpoint

	for the delete mod operation.

	Typically these are written to a http.Request.
*/
type DeleteModParams struct {

	/* ModID.

	   A mod UUID or slug
	*/
	ModID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete mod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteModParams) WithDefaults() *DeleteModParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete mod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteModParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete mod params
func (o *DeleteModParams) WithTimeout(timeout time.Duration) *DeleteModParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mod params
func (o *DeleteModParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mod params
func (o *DeleteModParams) WithContext(ctx context.Context) *DeleteModParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mod params
func (o *DeleteModParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mod params
func (o *DeleteModParams) WithHTTPClient(client *http.Client) *DeleteModParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mod params
func (o *DeleteModParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModID adds the modID to the delete mod params
func (o *DeleteModParams) WithModID(modID string) *DeleteModParams {
	o.SetModID(modID)
	return o
}

// SetModID adds the modId to the delete mod params
func (o *DeleteModParams) SetModID(modID string) {
	o.ModID = modID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteModParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mod_id
	if err := r.SetPathParam("mod_id", o.ModID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
