// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/v1/models"
)

// ListModUsersReader is a Reader for the ListModUsers structure.
type ListModUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListModUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListModUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewListModUsersForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListModUsersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListModUsersOK creates a ListModUsersOK with default headers values
func NewListModUsersOK() *ListModUsersOK {
	return &ListModUsersOK{}
}

/* ListModUsersOK describes a response with status code 200, with default header values.

A collection of mod users
*/
type ListModUsersOK struct {
	Payload []*models.UserMod
}

func (o *ListModUsersOK) Error() string {
	return fmt.Sprintf("[GET /mods/{mod_id}/users][%d] listModUsersOK  %+v", 200, o.Payload)
}
func (o *ListModUsersOK) GetPayload() []*models.UserMod {
	return o.Payload
}

func (o *ListModUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListModUsersForbidden creates a ListModUsersForbidden with default headers values
func NewListModUsersForbidden() *ListModUsersForbidden {
	return &ListModUsersForbidden{}
}

/* ListModUsersForbidden describes a response with status code 403, with default header values.

User is not authorized
*/
type ListModUsersForbidden struct {
	Payload *models.GeneralError
}

func (o *ListModUsersForbidden) Error() string {
	return fmt.Sprintf("[GET /mods/{mod_id}/users][%d] listModUsersForbidden  %+v", 403, o.Payload)
}
func (o *ListModUsersForbidden) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *ListModUsersForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListModUsersDefault creates a ListModUsersDefault with default headers values
func NewListModUsersDefault(code int) *ListModUsersDefault {
	return &ListModUsersDefault{
		_statusCode: code,
	}
}

/* ListModUsersDefault describes a response with status code -1, with default header values.

Some error unrelated to the handler
*/
type ListModUsersDefault struct {
	_statusCode int

	Payload *models.GeneralError
}

// Code gets the status code for the list mod users default response
func (o *ListModUsersDefault) Code() int {
	return o._statusCode
}

func (o *ListModUsersDefault) Error() string {
	return fmt.Sprintf("[GET /mods/{mod_id}/users][%d] ListModUsers default  %+v", o._statusCode, o.Payload)
}
func (o *ListModUsersDefault) GetPayload() *models.GeneralError {
	return o.Payload
}

func (o *ListModUsersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GeneralError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
