// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kleister/kleister-go/v1/models"
)

// NewPermitModUserParams creates a new PermitModUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPermitModUserParams() *PermitModUserParams {
	return &PermitModUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPermitModUserParamsWithTimeout creates a new PermitModUserParams object
// with the ability to set a timeout on a request.
func NewPermitModUserParamsWithTimeout(timeout time.Duration) *PermitModUserParams {
	return &PermitModUserParams{
		timeout: timeout,
	}
}

// NewPermitModUserParamsWithContext creates a new PermitModUserParams object
// with the ability to set a context for a request.
func NewPermitModUserParamsWithContext(ctx context.Context) *PermitModUserParams {
	return &PermitModUserParams{
		Context: ctx,
	}
}

// NewPermitModUserParamsWithHTTPClient creates a new PermitModUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewPermitModUserParamsWithHTTPClient(client *http.Client) *PermitModUserParams {
	return &PermitModUserParams{
		HTTPClient: client,
	}
}

/* PermitModUserParams contains all the parameters to send to the API endpoint
   for the permit mod user operation.

   Typically these are written to a http.Request.
*/
type PermitModUserParams struct {

	/* ModID.

	   A mod UUID or slug
	*/
	ModID string

	/* ModUser.

	   The mod user data to update
	*/
	ModUser *models.ModUserParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the permit mod user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PermitModUserParams) WithDefaults() *PermitModUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the permit mod user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PermitModUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the permit mod user params
func (o *PermitModUserParams) WithTimeout(timeout time.Duration) *PermitModUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the permit mod user params
func (o *PermitModUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the permit mod user params
func (o *PermitModUserParams) WithContext(ctx context.Context) *PermitModUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the permit mod user params
func (o *PermitModUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the permit mod user params
func (o *PermitModUserParams) WithHTTPClient(client *http.Client) *PermitModUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the permit mod user params
func (o *PermitModUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModID adds the modID to the permit mod user params
func (o *PermitModUserParams) WithModID(modID string) *PermitModUserParams {
	o.SetModID(modID)
	return o
}

// SetModID adds the modId to the permit mod user params
func (o *PermitModUserParams) SetModID(modID string) {
	o.ModID = modID
}

// WithModUser adds the modUser to the permit mod user params
func (o *PermitModUserParams) WithModUser(modUser *models.ModUserParams) *PermitModUserParams {
	o.SetModUser(modUser)
	return o
}

// SetModUser adds the modUser to the permit mod user params
func (o *PermitModUserParams) SetModUser(modUser *models.ModUserParams) {
	o.ModUser = modUser
}

// WriteToRequest writes these params to a swagger request
func (o *PermitModUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mod_id
	if err := r.SetPathParam("mod_id", o.ModID); err != nil {
		return err
	}
	if o.ModUser != nil {
		if err := r.SetBodyParam(o.ModUser); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
