// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExternalCallbackParams creates a new ExternalCallbackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalCallbackParams() *ExternalCallbackParams {
	return &ExternalCallbackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalCallbackParamsWithTimeout creates a new ExternalCallbackParams object
// with the ability to set a timeout on a request.
func NewExternalCallbackParamsWithTimeout(timeout time.Duration) *ExternalCallbackParams {
	return &ExternalCallbackParams{
		timeout: timeout,
	}
}

// NewExternalCallbackParamsWithContext creates a new ExternalCallbackParams object
// with the ability to set a context for a request.
func NewExternalCallbackParamsWithContext(ctx context.Context) *ExternalCallbackParams {
	return &ExternalCallbackParams{
		Context: ctx,
	}
}

// NewExternalCallbackParamsWithHTTPClient creates a new ExternalCallbackParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalCallbackParamsWithHTTPClient(client *http.Client) *ExternalCallbackParams {
	return &ExternalCallbackParams{
		HTTPClient: client,
	}
}

/*
ExternalCallbackParams contains all the parameters to send to the API endpoint

	for the external callback operation.

	Typically these are written to a http.Request.
*/
type ExternalCallbackParams struct {

	/* Provider.

	   An identifier for the auth provider
	*/
	Provider string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalCallbackParams) WithDefaults() *ExternalCallbackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalCallbackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external callback params
func (o *ExternalCallbackParams) WithTimeout(timeout time.Duration) *ExternalCallbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external callback params
func (o *ExternalCallbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external callback params
func (o *ExternalCallbackParams) WithContext(ctx context.Context) *ExternalCallbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external callback params
func (o *ExternalCallbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external callback params
func (o *ExternalCallbackParams) WithHTTPClient(client *http.Client) *ExternalCallbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external callback params
func (o *ExternalCallbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the external callback params
func (o *ExternalCallbackParams) WithProvider(provider string) *ExternalCallbackParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the external callback params
func (o *ExternalCallbackParams) SetProvider(provider string) {
	o.Provider = provider
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalCallbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
