// Code generated by go-swagger; DO NOT EDIT.

package forge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListForgeBuildsParams creates a new ListForgeBuildsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListForgeBuildsParams() *ListForgeBuildsParams {
	return &ListForgeBuildsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListForgeBuildsParamsWithTimeout creates a new ListForgeBuildsParams object
// with the ability to set a timeout on a request.
func NewListForgeBuildsParamsWithTimeout(timeout time.Duration) *ListForgeBuildsParams {
	return &ListForgeBuildsParams{
		timeout: timeout,
	}
}

// NewListForgeBuildsParamsWithContext creates a new ListForgeBuildsParams object
// with the ability to set a context for a request.
func NewListForgeBuildsParamsWithContext(ctx context.Context) *ListForgeBuildsParams {
	return &ListForgeBuildsParams{
		Context: ctx,
	}
}

// NewListForgeBuildsParamsWithHTTPClient creates a new ListForgeBuildsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListForgeBuildsParamsWithHTTPClient(client *http.Client) *ListForgeBuildsParams {
	return &ListForgeBuildsParams{
		HTTPClient: client,
	}
}

/* ListForgeBuildsParams contains all the parameters to send to the API endpoint
   for the list forge builds operation.

   Typically these are written to a http.Request.
*/
type ListForgeBuildsParams struct {

	/* ForgeID.

	   A forge UUID or slug
	*/
	ForgeID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list forge builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgeBuildsParams) WithDefaults() *ListForgeBuildsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list forge builds params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgeBuildsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list forge builds params
func (o *ListForgeBuildsParams) WithTimeout(timeout time.Duration) *ListForgeBuildsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list forge builds params
func (o *ListForgeBuildsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list forge builds params
func (o *ListForgeBuildsParams) WithContext(ctx context.Context) *ListForgeBuildsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list forge builds params
func (o *ListForgeBuildsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list forge builds params
func (o *ListForgeBuildsParams) WithHTTPClient(client *http.Client) *ListForgeBuildsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list forge builds params
func (o *ListForgeBuildsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForgeID adds the forgeID to the list forge builds params
func (o *ListForgeBuildsParams) WithForgeID(forgeID string) *ListForgeBuildsParams {
	o.SetForgeID(forgeID)
	return o
}

// SetForgeID adds the forgeId to the list forge builds params
func (o *ListForgeBuildsParams) SetForgeID(forgeID string) {
	o.ForgeID = forgeID
}

// WriteToRequest writes these params to a swagger request
func (o *ListForgeBuildsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param forge_id
	if err := r.SetPathParam("forge_id", o.ForgeID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
