// Code generated by go-swagger; DO NOT EDIT.

package forge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListForgesParams creates a new ListForgesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListForgesParams() *ListForgesParams {
	return &ListForgesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListForgesParamsWithTimeout creates a new ListForgesParams object
// with the ability to set a timeout on a request.
func NewListForgesParamsWithTimeout(timeout time.Duration) *ListForgesParams {
	return &ListForgesParams{
		timeout: timeout,
	}
}

// NewListForgesParamsWithContext creates a new ListForgesParams object
// with the ability to set a context for a request.
func NewListForgesParamsWithContext(ctx context.Context) *ListForgesParams {
	return &ListForgesParams{
		Context: ctx,
	}
}

// NewListForgesParamsWithHTTPClient creates a new ListForgesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListForgesParamsWithHTTPClient(client *http.Client) *ListForgesParams {
	return &ListForgesParams{
		HTTPClient: client,
	}
}

/*
ListForgesParams contains all the parameters to send to the API endpoint

	for the list forges operation.

	Typically these are written to a http.Request.
*/
type ListForgesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list forges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgesParams) WithDefaults() *ListForgesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list forges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list forges params
func (o *ListForgesParams) WithTimeout(timeout time.Duration) *ListForgesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list forges params
func (o *ListForgesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list forges params
func (o *ListForgesParams) WithContext(ctx context.Context) *ListForgesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list forges params
func (o *ListForgesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list forges params
func (o *ListForgesParams) WithHTTPClient(client *http.Client) *ListForgesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list forges params
func (o *ListForgesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListForgesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
