// Code generated by go-swagger; DO NOT EDIT.

package fabric

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateFabricParams creates a new UpdateFabricParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateFabricParams() *UpdateFabricParams {
	return &UpdateFabricParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFabricParamsWithTimeout creates a new UpdateFabricParams object
// with the ability to set a timeout on a request.
func NewUpdateFabricParamsWithTimeout(timeout time.Duration) *UpdateFabricParams {
	return &UpdateFabricParams{
		timeout: timeout,
	}
}

// NewUpdateFabricParamsWithContext creates a new UpdateFabricParams object
// with the ability to set a context for a request.
func NewUpdateFabricParamsWithContext(ctx context.Context) *UpdateFabricParams {
	return &UpdateFabricParams{
		Context: ctx,
	}
}

// NewUpdateFabricParamsWithHTTPClient creates a new UpdateFabricParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateFabricParamsWithHTTPClient(client *http.Client) *UpdateFabricParams {
	return &UpdateFabricParams{
		HTTPClient: client,
	}
}

/*
UpdateFabricParams contains all the parameters to send to the API endpoint

	for the update fabric operation.

	Typically these are written to a http.Request.
*/
type UpdateFabricParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update fabric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFabricParams) WithDefaults() *UpdateFabricParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update fabric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateFabricParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update fabric params
func (o *UpdateFabricParams) WithTimeout(timeout time.Duration) *UpdateFabricParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update fabric params
func (o *UpdateFabricParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update fabric params
func (o *UpdateFabricParams) WithContext(ctx context.Context) *UpdateFabricParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update fabric params
func (o *UpdateFabricParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update fabric params
func (o *UpdateFabricParams) WithHTTPClient(client *http.Client) *UpdateFabricParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update fabric params
func (o *UpdateFabricParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFabricParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
