// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BuildVersionParams build version params
//
// swagger:model build_version_params
type BuildVersionParams struct {

	// mod
	// Required: true
	Mod *string `json:"mod"`

	// version
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this build version params
func (m *BuildVersionParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildVersionParams) validateMod(formats strfmt.Registry) error {

	if err := validate.Required("mod", "body", m.Mod); err != nil {
		return err
	}

	return nil
}

func (m *BuildVersionParams) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this build version params based on context it is used
func (m *BuildVersionParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuildVersionParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildVersionParams) UnmarshalBinary(b []byte) error {
	var res BuildVersionParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
