// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamPackParams team pack params
// swagger:model team_pack_params
type TeamPackParams struct {

	// pack
	// Required: true
	Pack *string `json:"pack"`

	// perm
	// Required: true
	Perm *string `json:"perm"`

	// team
	// Required: true
	Team *string `json:"team"`
}

// Validate validates this team pack params
func (m *TeamPackParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePack(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePerm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTeam(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TeamPackParams) validatePack(formats strfmt.Registry) error {

	if err := validate.Required("pack", "body", m.Pack); err != nil {
		return err
	}

	return nil
}

func (m *TeamPackParams) validatePerm(formats strfmt.Registry) error {

	if err := validate.Required("perm", "body", m.Perm); err != nil {
		return err
	}

	return nil
}

func (m *TeamPackParams) validateTeam(formats strfmt.Registry) error {

	if err := validate.Required("team", "body", m.Team); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TeamPackParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamPackParams) UnmarshalBinary(b []byte) error {
	var res TeamPackParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
